build(deps): update sentry-javascript monorepo to ^10.15.0 (#5336)
Coming soon: The Renovate bot (GitHub App) will be renamed to Mend. PRs
from Renovate will soon appear from 'Mend'. Learn more
[here](https://redirect.github.com/renovatebot/renovate/discussions/37842).

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
|
[@sentry/nextjs](https://redirect.github.com/getsentry/sentry-javascript/tree/master/packages/nextjs)
([source](https://redirect.github.com/getsentry/sentry-javascript)) |
[`^10.14.0` ->
`^10.15.0`](https://renovatebot.com/diffs/npm/@sentry%2fnextjs/10.14.0/10.15.0)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@sentry%2fnextjs/10.15.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@sentry%2fnextjs/10.15.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@sentry%2fnextjs/10.14.0/10.15.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@sentry%2fnextjs/10.14.0/10.15.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[@sentry/profiling-node](https://redirect.github.com/getsentry/sentry-javascript/tree/master/packages/profiling-node)
([source](https://redirect.github.com/getsentry/sentry-javascript)) |
[`^10.14.0` ->
`^10.15.0`](https://renovatebot.com/diffs/npm/@sentry%2fprofiling-node/10.14.0/10.15.0)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@sentry%2fprofiling-node/10.15.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@sentry%2fprofiling-node/10.15.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@sentry%2fprofiling-node/10.14.0/10.15.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@sentry%2fprofiling-node/10.14.0/10.15.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>getsentry/sentry-javascript (@&#8203;sentry/nextjs)</summary>

###
[`v10.15.0`](https://redirect.github.com/getsentry/sentry-javascript/releases/tag/10.15.0)

[Compare
Source](https://redirect.github.com/getsentry/sentry-javascript/compare/10.14.0...10.15.0)

##### Important Changes

- **feat(cloudflare): Add honoIntegration with error-filtering function
([#&#8203;17743](https://redirect.github.com/getsentry/sentry-javascript/pull/17743))**

This release adds a `honoIntegration` to `@sentry/cloudflare`, which
exposes a `shouldHandleError` function that lets you define which errors
in `onError` should be captured.
By default, Sentry captures exceptions with `error.status >= 500 ||
error.status <= 299`.

The integration is added by default, and it's possible to modify this
behavior like this:

  ```js
   integrations: [
     honoIntegration({
shouldHandleError: (err) => true; // always capture exceptions in
onError
     })
   ]
  ```

- **feat(node): Add instrumentation for hono handler
([#&#8203;17428](https://redirect.github.com/getsentry/sentry-javascript/pull/17428))**

This PR enhances the Hono integration by adding comprehensive handler
instrumentation, error handling capabilities.

- **feat(aws): Enable Lambda extension by default when using the Lamba
layer
([#&#8203;17684](https://redirect.github.com/getsentry/sentry-javascript/pull/17684))**

- **feat(browser): Add `setActiveSpanInBrowser` to set an active span in
the browser
([#&#8203;17714](https://redirect.github.com/getsentry/sentry-javascript/pull/17714))**

This PR adds a feature to the browser SDKs only: Making an inactive span
active. We do this to enable use cases where having a span only being
active in the callback is not practical.

##### Other Changes

- fix(browser): Improve handling of `0` and `undefined` resource timing
values
([#&#8203;17751](https://redirect.github.com/getsentry/sentry-javascript/pull/17751))
- ref(nextjs): Display build compatibility warning for webpack
([#&#8203;17746](https://redirect.github.com/getsentry/sentry-javascript/pull/17746))

<details>
  <summary> <strong>Internal Changes</strong> </summary>

- docs: Reword changelog for google gen ai instrumentation
([#&#8203;17753](https://redirect.github.com/getsentry/sentry-javascript/pull/17753))
- build: Add `@typescript-eslint/no-unnecessary-type-assertion` rule
([#&#8203;17728](https://redirect.github.com/getsentry/sentry-javascript/pull/17728))
- build: Update TS target to `es2020` everywhere
([#&#8203;17709](https://redirect.github.com/getsentry/sentry-javascript/pull/17709))
- chore: Add external contributor to CHANGELOG.md
([#&#8203;17745](https://redirect.github.com/getsentry/sentry-javascript/pull/17745))

</details>

Work in this release was contributed by
[@&#8203;Karibash](https://redirect.github.com/Karibash). Thank you for
your contribution!

#### Bundle size 📦

| Path | Size |
|
-----------------------------------------------------------------------------------------------------
| --------- |
| [@&#8203;sentry/browser](https://redirect.github.com/sentry/browser) |
23.69 KB |
| [@&#8203;sentry/browser](https://redirect.github.com/sentry/browser) -
with treeshaking flags | 22.24 KB |
| [@&#8203;sentry/browser](https://redirect.github.com/sentry/browser)
(incl. Tracing) | 39.49 KB |
| [@&#8203;sentry/browser](https://redirect.github.com/sentry/browser)
(incl. Tracing, Replay) | 76.96 KB |
| [@&#8203;sentry/browser](https://redirect.github.com/sentry/browser)
(incl. Tracing, Replay) - with treeshaking flags | 66.87 KB |
| [@&#8203;sentry/browser](https://redirect.github.com/sentry/browser)
(incl. Tracing, Replay with Canvas) | 81.52 KB |
| [@&#8203;sentry/browser](https://redirect.github.com/sentry/browser)
(incl. Tracing, Replay, Feedback) | 93.44 KB |
| [@&#8203;sentry/browser](https://redirect.github.com/sentry/browser)
(incl. Feedback) | 40.01 KB |
| [@&#8203;sentry/browser](https://redirect.github.com/sentry/browser)
(incl. sendFeedback) | 28.24 KB |
| [@&#8203;sentry/browser](https://redirect.github.com/sentry/browser)
(incl. FeedbackAsync) | 33.05 KB |
| [@&#8203;sentry/react](https://redirect.github.com/sentry/react) |
25.37 KB |
| [@&#8203;sentry/react](https://redirect.github.com/sentry/react)
(incl. Tracing) | 41.42 KB |
| [@&#8203;sentry/vue](https://redirect.github.com/sentry/vue) | 28.11
KB |
| [@&#8203;sentry/vue](https://redirect.github.com/sentry/vue) (incl.
Tracing) | 41.25 KB |
| [@&#8203;sentry/svelte](https://redirect.github.com/sentry/svelte) |
23.72 KB |
| CDN Bundle | 25.17 KB |
| CDN Bundle (incl. Tracing) | 39.39 KB |
| CDN Bundle (incl. Tracing, Replay) | 74.76 KB |
| CDN Bundle (incl. Tracing, Replay, Feedback) | 80.13 KB |
| CDN Bundle - uncompressed | 73.6 KB |
| CDN Bundle (incl. Tracing) - uncompressed | 116.59 KB |
| CDN Bundle (incl. Tracing, Replay) - uncompressed | 229.02 KB |
| CDN Bundle (incl. Tracing, Replay, Feedback) - uncompressed | 241.48
KB |
| [@&#8203;sentry/nextjs](https://redirect.github.com/sentry/nextjs)
(client) | 43.38 KB |
|
[@&#8203;sentry/sveltekit](https://redirect.github.com/sentry/sveltekit)
(client) | 39.9 KB |
|
[@&#8203;sentry/node-core](https://redirect.github.com/sentry/node-core)
| 48.85 KB |
| [@&#8203;sentry/node](https://redirect.github.com/sentry/node) |
149.25 KB |
| [@&#8203;sentry/node](https://redirect.github.com/sentry/node) -
without tracing | 89.79 KB |
|
[@&#8203;sentry/aws-serverless](https://redirect.github.com/sentry/aws-serverless)
| 102.92 KB |

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about these
updates again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/inabagumi/shinju-date).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0MS45Ny4xMCIsInVwZGF0ZWRJblZlciI6IjQxLjk3LjEwIiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6WyJkZXBlbmRlbmNpZXMiXX0=-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>